GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWNlcCIsImlhdCI6MTY1NDA3MDk0MywiZXhwIjoxNjU0MDcwOTY4fQ.WaI-cwzaRyzu4Fb2Z_SxPlzQX-LP98bBaOqBjGIQL1s

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWNlcCIsImlhdCI6MTY1NDA3MDkyOX0.LSgpJNBmiNtyfTlUMHE6eV2NpfQN_ZQWt6kQaJtmyCM"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWNlcCIsImlhdCI6MTY1NDA3MDkyOX0.LSgpJNBmiNtyfTlUMHE6eV2NpfQN_ZQWt6kQaJtmyCM"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "acep"
}